# Generated by Django 4.2.7 on 2023-12-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enums', '0003_remove_scaleprotocol_id_remove_vatrate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('anpr', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=2)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='enums.scaleprotocol')),
            ],
        ),
    ]
