# Generated by Django 4.2.9 on 2024-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcamera',
            name='anpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scale',
            name='port',
            field=models.CharField(),
        ),
    ]
