# Generated by Django 4.2.7 on 2023-12-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_ipcamera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPCamera',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='protocol',
        ),
    ]
