# Generated by Django 4.2.7 on 2023-12-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_delete_ipcamera_remove_scale_protocol'),
        ('documents', '0016_alter_vehicletare_scale_alter_weighing_scale_gross_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
