# Generated by Django 4.2.9 on 2024-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_alter_contract_id_alter_counterparty_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_plate',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
