# Generated by Django 4.2.7 on 2023-11-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('id_object', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
            ],
        ),
    ]
