# Generated by Django 4.2.7 on 2023-12-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together={('key', 'id_object')},
        ),
    ]
