# Generated by Django 2.2.28 on 2023-10-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_auto_20231025_1108'),
        ('enums', '0002_vatrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('includes_vat', models.BooleanField(default=False)),
                ('summa', models.FloatField()),
                ('vat_summa', models.FloatField()),
                ('summa_with_vat', models.FloatField()),
                ('doc_no', models.SmallIntegerField(blank=True, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Contract')),
                ('counterparty', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Counterparty')),
                ('driver', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Driver')),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Organization')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Product')),
                ('vat_rate', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='enums.VATRate')),
                ('warehouse', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='catalogs.Warehouse')),
            ],
        ),
    ]
