# Generated by Django 2.2.28 on 2023-10-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20231025_1108'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighing',
            name='date_gross',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='date_tare',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='doc_gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='doc_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='doc_tare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='scale_gross',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grosses', to='catalogs.Scale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weighing',
            name='scale_tare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tares', to='catalogs.Scale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weighing',
            name='tare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighing',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weighing',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WeighingVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('tare', models.FloatField(blank=True, null=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.Scale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.Vehicle')),
            ],
        ),
    ]
