# Generated by Django 2.2.28 on 2023-11-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20231101_1346'),
        ('documents', '0002_auto_20231026_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeighingVehicle',
            new_name='VehicleTare',
        ),
    ]
