# Generated by Django 2.2.28 on 2023-11-03 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20231102_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletare',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vehicletare',
            name='tare',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='deviation',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='doc_gross',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='doc_net',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='doc_tare',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='gross',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='net',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='tare',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
