# Generated by Django 2.2.28 on 2023-11-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20231103_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighing',
            name='date_gross',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='doc_date',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='doc_gross',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='doc_net',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='doc_no',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='doc_tare',
        ),
        migrations.AlterField(
            model_name='weighing',
            name='gross',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
