# Generated by Django 2.2.28 on 2023-11-04 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20231104_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighing',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Contract'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Counterparty'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Driver'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Organization'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Product'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='scale_tare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tares', to='catalogs.Scale'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='summa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='summa_with_vat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enums.VATRate'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='vat_summa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Warehouse'),
        ),
    ]
