# Generated by Django 2.2.28 on 2023-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20231104_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighing',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='summa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='summa_with_vat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='vat_summa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
