# Generated by Django 2.2.28 on 2023-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20231104_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighing',
            name='date',
        ),
        migrations.AddField(
            model_name='weighing',
            name='date_gross',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletare',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
