# Generated by Django 2.2.28 on 2023-11-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20231106_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletare',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Scale'),
        ),
    ]
