# Generated by Django 2.2.28 on 2023-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20231106_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletare',
            name='tare',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='gross',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
