# Generated by Django 2.2.28 on 2023-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20231107_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighing',
            name='net',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='tare',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
