# Generated by Django 2.2.28 on 2023-11-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20231107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighing',
            name='scale_gross',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grosses', to='catalogs.Scale'),
        ),
    ]
