# Generated by Django 4.2.9 on 2024-01-11 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_vehicletare_photo_1_vehicletare_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletare',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
