# Generated by Django 4.2.9 on 2024-01-11 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_vehicletare_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='weighing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='date_gross',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
