# Generated by Django 4.2.9 on 2024-01-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_weighing_photo_1_weighing_photo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighing',
            name='includes_vat',
        ),
    ]
