# Generated by Django 4.2.9 on 2024-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_remove_weighing_includes_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighing',
            name='includes_vat',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
