# Generated by Django 4.2.9 on 2024-01-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
