# Generated by Django 2.2.28 on 2023-10-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
    ]
