# Generated by Django 4.2.7 on 2023-11-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enums', '0002_vatrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaleprotocol',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vatrate',
            name='id',
        ),
        migrations.AlterField(
            model_name='scaleprotocol',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
