# Generated by Django 4.2.9 on 2024-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enums', '0003_remove_scaleprotocol_id_remove_vatrate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
